### ISSUE TITLE
System tray menu items throw an exception

### ISSUE THREAD

**Issue by Ayrler** [felixse/FluentTerminal#739]
When using any of the menu items of FluentTerminal in the system tray an unhandled exception occurs.    
I have manually installed the app and did not test other ways to install it.

```
************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at FluentTerminal.SystemTray.SystemTrayApplicationContext.NewWindow(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by felixse** [comment]
Does this only occur when starting from the system tray?

**Comment by Ayrler** [comment]
I am not sure I understand exactly the meaning behind "starting from the system tray".
These errors are thrown when I right click on the system tray icon and choose any of the items: "New terminal" or "Show Terminal".
